### ISSUE TITLE
2.3.3 no display on frontend

### ISSUE THREAD

**Issue by markalston** [Monetra/monetra_magento2#11]
Not sure if this modules works on 2.3.3 but if so I'm not getting any frame on the frontend at checkout.  Testing with the test server to make sure it isn't my monetra server issue.
Thanks.

**Comment by gregweston** [comment]
The module should work on 2.3.3. Are you seeing the iframe request in your browser's developer console? This would be a POST request to the Monetra server. If so, what is the response? If not, are you seeing any Javascript errors in the console?

**Comment by markalston** [comment]
I'm not seeing any iframe requests.  Otherwise there are no javascript errors.  I do see monetra.js being loaded but I don't see client-ticket-method.js loaded and I think that I should.

I disabled all extra modules and even tried using Luma theme.  

I am wondering if my issues are due to the change to the new payment method facade method?
https://devdocs.magento.com/guides/v2.3/payments-integrations/base-integration/facade-configuration.html

But if the modules is working for other people on 2.3 then  something else must be the issue.

**Comment by bradh352** [comment]
Are you using TranSafe or your own Monetra.  If using Monetra, what version of Monetra are you running?

**Comment by markalston** [comment]
Using the transafe test server for now to ensure that the problem isn't on my end.

**Comment by markalston** [comment]
Using the dropdown option and cleared out all the host settings. But from reading the code simply selecting the test server should override those settings anyway.

**Comment by markalston** [comment]
Been messing with this for two days with no success.  If someone can confirm for me that this has actually been tested with monetra 2.3.x and more helpfully 2.3.3 and 2.3.4 that would be great.  At least it will point me toward whether it is a code issue or a site issue. Thanks!

**Comment by markalston** [comment]
Getting farther.  Added the following to ClientTicket.php and now at least the option shows up.  Now it just shows "Authentication failure Payment form could not be loaded" in the space where the cc info should be.

```
        public function isAvailable(\Magento\Quote\Api\Data\CartInterface $quote = NULL){
               return $this->getConfigData('active') || $this->getConfigData('active');
        }
```

**Comment by markalston** [comment]
And now with the proper credentials for the test server it is now showing properly.

Looks like the isAvailable public function needs to be there. Mine above is just a copy/paste from stack so you might want to tweak it.

**Comment by gregweston** [comment]
Mark, your pull request appears to resolve this issue. Thanks!
