### ISSUE TITLE
Client Ticket HMAC Timestamp issue

### ISSUE THREAD

**Issue by gamort** [Monetra/monetra_magento2#4]
When customers take a while to fill in the checkout form on a one page checkout[where the timestamp is generated when the entire form is loaded] this can result in the timestamp being stale by the time the payment is submitted.

The response displayed to the customer is a generic "payment error" message and there is no indication of what can be done to resubmit the payment[short of reloading the entire checkout screen, I don't think there is one?]

When payment is rejected due to a timestamp, there should be a method to continue and resubmit.
![screen shot 2016-11-07 at 3 08 34 pm](https://cloud.githubusercontent.com/assets/15091656/20074339/d3ed8100-a4fd-11e6-976a-3811272b92ee.png)

**Comment by gregweston** [comment]
Hi Gary,

Thanks for reporting this. Most likely what we'll do is add an automatic page reload after a certain amount of time has passed to generate a new hmac based on the current time.
