### ISSUE TITLE
Insufficient Exception Handling

### ISSUE THREAD

**Issue by gamort** [Monetra/monetra_magento2#5]
The javascript code used by the web client to generate a client ticket does not have sufficient exception handling:  It expects to receive an xml response from the Monetra Payment server which will contain a the "client ticket".  This ticket is generated/returned whether or not the payment is authorized or rejected - and it is sent directly on to the Magento server.   The Magento server will then determine if it was a success, failure, or something else and can then provide the customer with instructions on how to proceed.

The problem is that the script does not have sufficient exception handling.   During implementation for University Products, https://www.universityproducts.com/ we have encountered 3 different circumstances where instead of receiving an xml response, the response is something else - either html generated by the Monetra server or text from web browser itself.   When that happens, the "error" function on line 63 is invoked
https://github.com/Monetra/monetra_magento2/blob/master/view/base/web/js/client-ticket-request.js#L63

This displays a hard coded, generic message defined on lines 9 and 10 and does not provide any way for the customer to determine what they need to do next[see issue 4 for an example]

For reference, we have had this occur under the following situations:
1) The HMAC ticket timestamp is not inside the window.   The Monetra server returns an html message instead of xml and the web browser hangs.  If instead it had returned a ticket which the Magento server could use to lookup why the payment failed, the Magento server could redirect back to the checkout page with a message about "checkout took too long to complete, please re-enter payment information" or something

2) The web browser refuses to accept the SSL certificate of the remote server.  In that case, Google Chrome will generate an html "connection is not secure" message.   At that point the customer would have to contact the ecommerce store since there is no way to force the browser to allow the submission - but at least the customer could be given instructions.

3) When a ticket is submitted, the Monetra server will double check that there really is a web server it is being submitted for by checking something with the Magento server.  During QA, as a final test we updated the Magento configuration to use the www.universityproducts.com domain before updating the DNS.  We then proceeded to test by editing the hosts file on the local systems so they could reach the server.   When submitting the payment, the Monetra server would try to connect to www.universityproducts.com using the ip address from DNS and when it failed, the payment would be aborted.

This is not meant to be a comprehensive list of all possibilities.  My assumption is that during development it was felt that it was almost impossible for the web client to not receive some form of valid xml response from the Monetra server, so no exception handling was created for errors.  Based on the above as well as all the other possible non-xml responses that the Monetra payment server might return - exception handling should be added to deal with these.... exceptional circumstances.

**Comment by gregweston** [comment]
Hi Gary,

I've added some more situation-specific error handling and messaging during the checkout process. If a 400 response is received from the Monetra server when trying to generate the ticket, the error modal will indicate that a page reload may resolve the issue, and the modal's "dismiss" button will automatically reload the page. If any other error code is received (including a browser-generated 0 code, indicating that the Monetra server's SSL cert was rejected), the user will be instructed to contact support.

**Comment by gamort** [comment]
Thanks Greg!   I will go ahead and close this issue - the client had been handling their next upgrade as far as I know and was monitoring the issue.
