### ISSUE TITLE
Password Field Re-encrypted on Save

### ISSUE THREAD

**Issue by nthurston** [Monetra/monetra_magento2#7]
On magento 2.2.6, the Monetra password field is re-encrypted every time you save the config.  So it is taking the encrypted data and re-encrypting that, which ends up causing an hmac-sha256 mismatch when you go to place the order because the password cannot be decrypted properly.

Possibly related to this magento issue:
https://github.com/magento/magento2/issues/12581

Though there are a few other magento modules using encrypted fields that do not have the same issue.  Authorize.net direct post for example.

Possibly related to the type on the password field in system.xml.  Looks like that should be obscure, though I tried switching to that and the issue persisted.

**Comment by nthurston** [comment]
On a second pass, it looks like changing that field type from "password" to "obscure" in system.xml does fix the issue.

**Comment by gregweston** [comment]
Thanks for reporting this. We should have an update out to address this within the next day or so.

**Comment by gregweston** [comment]
Fixed in https://github.com/Monetra/monetra_magento2/commit/d55349c79d45506a224671d1914d6194557e2ad8
