### ISSUE TITLE
System.xml required_payment_fields "can_be_empty" is not allowed

### ISSUE THREAD

**Issue by nthurston** [Monetra/monetra_magento2#9]
Looks like the can_be_empty attribute is not allowed on the field element anymore.  In dev mode you'll get an error like such:

`Element 'field', attribute 'can_be_empty': The attribute 'can_be_empty' is not allowed.`

I added it as a child element instead and that works:

```
<field id="required_payment_fields" translate="label" type="multiselect" sortOrder="170" showInDefault="1" showInWebsite="1" showInStore="0">
    <label>Required Payment Fields</label>
    <source_model>Monetra\Monetra\Model\Source\RequiredPaymentFields</source_model>
    <can_be_empty>1</can_be_empty>
</field>
```

**Comment by gregweston** [comment]
Thanks for reporting this. Fixed in https://github.com/Monetra/monetra_magento2/commit/63dd60b1346bdac3ebcf68fb5859264853b9daad
